### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by sneikki** [nuclearkittens/ot-projekti#1]
Koodikatselmointi on tehty repositoriosta, joka kloonattiin 3.5. kello 14:00.

Kloonasin repositorion ja suoritin projektin readmen ohjeiden mukaan. Ohjelma toimii moitteetta eikä kaadu tai ajaudu virhetilanteeseen. Kaikki komennot toimivat, ja lintteri antaa koodille hyvän arvosanan (8,71). Testejä projektissa ei kirjoitushetkellä ollut, joten testikattavuudesta ei voi palautetta antaa. Ohessa joitakin huomioita joita tein projektiin tutustuessani.

Metodit ja funktiot on nimetty hyvin ja kuvaavasti, samoin luokkien attribuutit. Lisäksi luokkien yksityisten attribuuttien ja metodien nimet alkavat käytännön mukaisesti alaviivalla. Myös decoratoreita on käytetty kuvaavasti. Kaiken kaikkiaan selkeää ja helppolukuista koodia.

Valtaosa tiedostoista on sijoitettu samaan hakemistoon. Jonkinlainen hierarkia erilaisten välillä voisi olla aiheellinen. Selkeä hakemistorakenne helpottaa kokonaiskuvan muodostamista sekä nopeuttaa projektiin tutustumista. Itse tiedostojen rakenne on selkeä, ja jokainen tiedosto sisältää vain sen kannalta olennaisen koodin. Tiedostot olisi tosin syytä nimetä vallitsevan käytännön mukaisesti snake\_casea käyttäen.

Funktiot ja metodit ovat pääosin kohtuullisen mittaisia ja toteuttavat niille kuuluvan asian. Lähinnä battledemo- ja battlesprite-luokassa on pari pitkähköä metodia, ja niistä voisi mahdollisuuksien mukaan yrittää eriyttää pienempiä kokonaisuuksia omiksi metodeikseen. Muun muassa ```calc_sprite_placement```-metodin for-silmukat näyttävät otollisilta erityttäviksi. En kuitenkaan pidä ko. metodeja ongelmallisina, koska rönsyily on rajoittunut muutamaan tapaukseen ja muutoin single responsibility -periaatetta on projektissa noudatettu mainiosti.

Ohjelma heittää ```pygame.error```-virheen aina kun ikkuna suljetaan. Tämä vaikuttaisi johtuvan siitä, että pääsilmukan tarkistus ei havaitse ikkunan sulkeutumista vaan siihen reagoidaan vasta ```_player_action```-metodissa. Lisäksi tapahtumankäsittelijä ainoastaaan sulkee pygamen, mutta pääsilmukan suoritus jatkuu edelleen ja jo suljettuun ikkunan yritetään renderöidä. Kannattaa laittaa esimerkiksi ```exit(0)``` tai vastaava ratkaisu pygamen sulkemisen jälkeen jotta ohjelman suoritus todella pysähtyy. Ohjelman toimintaahan tämä virhe ei haittaa, mutta toimivan ohjelman ei tulisi suljettaessakaan tulostaa stack tracea.

Mikäli mahdollista, peliin voisi lisätä tuen useammalle resoluutiolle tai ikkunan koon muutoksille. Jotkin window managerit eivät noista ohjelmien ikkunoiden kokotoiveista välitä, ja ainakin i3 leikkaa osan pois jos ikkunaa pienentää. Ei nyt mikään olennainen asia ja todellakaan sellainen mitä tarvitsisi lähteä muuttamaan, käyttäjän vikahan se on jos skaalailee vakiokokoiseksi tarkoitettua ikkunaa. Mutta tuollaisen havainnon tein. Yksinkertainen reponsiivisuus lienee kohtuullisella vaivalla toteutettavissa jos katsoo tarpeelliseksi.

Koodissa ei ole kummempaa huomatettavaa, eikä bugeja löytynyt aiemmin mainittua lukuun ottamatta. Tapahtumankäsittelyn korjaamalla oikein toimiva ohjelma. Plussaa hienoista grafiikoista. Hyvää työtä.

**Comment by nuclearkittens** [comment]
@varvikko 
Moikka!
Kiitos hyvästä palautteesta (--: Noi muut asiat onkin jo työn alla (yks murheenkryyni tää koko projekti, mut ehkä tästä vielä peli kasvaa kuukausien tai vuosien saatossa), mutta toi ikkunan skaalautuvuus ei varsinaisesti edes käynyt mielessä – tarkoitus oli tukea paria resoluutiota sitten joskus.

Pitänee katella tuota i3-ongelmaa, itelläni käytössä nimittäin fuksiläppärillä Cubbli ja himassa pyörii macOS 10.15, ja niillä Pygamen ikkunan kokoa ei edes voi muutella venyttämällä (tietääkseni) :D:D Ei o noi window managerit mitenkään tuttuja itselle, niin hyvä että sai tiedon tällasestaki.
